[package]
name = "rgb-interfaces"
version = "0.11.0-beta.6"
description = "Collection of the standard RGB smart contract interface"
keywords = ["bitcoin", "lightning", "rgb", "smart-contracts", "lnp-bp"]
categories = ["cryptography::cryptocurrencies"]
authors = ["Dr Maxim Orlovsky <orlovsky@lnp-bp.org>"]
homepage = "https://github.com/RGB-WG"
repository = "https://github.com/RGB-WG/rgb-interfaces"
rust-version = "1.75.0"  # rgb-std
edition = "2021"
license = "Apache-2.0"
readme = "README.md"

[[bin]]
name = "rgb-interfaces"
required-features = ["fs"]

[lib]
name = "ifaces"

[dependencies]
amplify = "4.6.0"
strict_encoding = "2.7.0-beta.4"
strict_types = "2.7.0-beta.4"
aluvm = "0.11.0-beta.6"
bp-core = "0.11.0-beta.6"
chrono = "0.4.37"
rgb-std = { version = "0.11.0-beta.6" }
serde_crate = { package = "serde", version = "1.0", optional = true }
serde_json = "1.0"
sha2 = "0.10.8"

[features]
default = []
all = ["serde", "fs"]
serde = ["serde_crate", "rgb-std/serde", "chrono/serde"]
fs = ["rgb-std/fs"]

[patch.crates-io]
bp-consensus = { git = "https://github.com/BP-WG/bp-core", branch = "master" }
bp-invoice = { git = "https://github.com/BP-WG/bp-std", branch = "master" }
rgb-core = { git = "https://github.com/RGB-WG/rgb-core", branch = "mining" }
rgb-invoice = { git = "https://github.com/RGB-WG/rgb-std", branch = "mining" }
rgb-std = { git = "https://github.com/RGB-WG/rgb-std", branch = "mining" }
